easy_admin:
    entities:
        CompanyContribution:
            class: App\Entity\Contribution
            controller: App\Controller\Admin\ContributionAdminController
            list:
                actions:
                    - {name: '-edit'}
                    - {name: '-delete'}
