easy_admin:
    entities:
        Hobby:
            class: App\Entity\Hobby
            controller: App\Controller\Admin\HobbyAdminController
            list:
                actions:
                    - {name: '-edit'}
                    - {name: '-new'}
                    - {name: '-delete'}
