# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        public: true
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    sensio_framework_extra.view.listener:
        alias: Sensio\Bundle\FrameworkExtraBundle\EventListener\TemplateListener

    serializer.form.error:
        class: App\Serializer\FormErrorSerializer
        public: true

    App\Service\Voter:
        arguments:
            - '@doctrine.orm.entity_manager'

    App\Command\CompanyCreateCommand:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.user_password_encoder.generic'
            - '@validator'
        tags:
            - { name: 'console.command' }

    App\Event\EasyAdminSubscriber:
        arguments:
            - '@App\Service\UserBudget'

    App\Service\UserBudget:
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'

    App\Service\UserRegisterByEmail:
        public: true
        arguments:
            - '%kernel.environment%'
            - '@doctrine.orm.default_entity_manager'

    App\Service\Registration:
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@security.user_password_encoder.generic'

